### ISSUE TITLE
up 5.17?

### ISSUE THREAD

**Issue by laincat** [sxx1314/pve-kernel#1]
https://github.com/fabianishere/pve-edge-kernel

**Comment by sxx1314** [comment]
有空测试一下看看稳定不稳定。5.17的tcp性能确实好不少。

**Comment by laincat** [comment]
等大佬的好消息。

**Comment by laincat** [comment]
The following packages will be REMOVED:
  proxmox-ve* pve-kernel-5.13* pve-kernel-5.13.19-2-pve* pve-kernel-5.13.19-6-pve*

删除旧的时候，提示删除 proxmox-ve* 可以删？

另外用：
https://github.com/jordanhillis/pvekclean

Warning, you're not running a PVE kernel

所以是可以删？

**Comment by sxx1314** [comment]
> The following packages will be REMOVED: proxmox-ve* pve-kernel-5.13* pve-kernel-5.13.19-2-pve* pve-kernel-5.13.19-6-pve*
> 
> 删除旧的时候，提示删除 proxmox-ve* 可以删？
> 
> 另外用： https://github.com/jordanhillis/pvekclean
> 
> Warning, you're not running a PVE kernel
> 
> 所以是可以删？

不放心的话你先删再装一遍即可，一般情况下包管理不会允许卸载当前kernel的依赖选项。
