### ISSUE TITLE
pve-headers-5.17.8-edge-dbgsym_5.17.8-1 安装报错

### ISSUE THREAD

**Issue by betaxab** [sxx1314/pve-kernel#3]
(Reading database ... 125643 files and directories currently installed.)
Preparing to unpack pve-headers-5.17.8-edge-dbgsym_5.17.8-1_amd64.deb ...
Unpacking pve-headers-5.17.8-edge-dbgsym (5.17.8-1) ...
dpkg: error processing archive pve-headers-5.17.8-edge-dbgsym_5.17.8-1_amd64.deb (--install):
 trying to overwrite '/usr/lib/debug/.build-id/14/3bf9f71f2eab9bb0199b7382a4f731c2b58739.debug', which is also in package pve-headers-5.17.5-edge-dbgsym 5.17.5-1
Errors were encountered while processing:
 pve-headers-5.17.8-edge-dbgsym_5.17.8-1_amd64.deb

必须手动卸载旧包才能安装上

**Comment by sxx1314** [comment]
这包装不装都不影响。看报错就明白，文件的md5都一模一样。
